api_platform:
  mapping:
    paths: ["%kernel.project_dir%/src/Entity"]
  formats:
    json: ["application/json"]
    jsonld: ["application/ld+json"]
    jsonhal: ["application/hal+json"]
    jsonapi: ["application/vnd.api+json"]
    xml: ["application/xml", "text/xml"]
    yaml: ["application/x-yaml"]
    csv: ["text/csv"]
    html: ["text/html"]
  swagger:
    versions: [3]

  collection:
    pagination:
      items_per_page: 30
      maximum_items_per_page: 200
      client_items_per_page: true
  eager_loading:
    force_eager: false
